# Generated by Django 5.2.13 on 2026-04-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_control_and_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livesession',
            name='iterations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesession',
            name='metrics_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesession',
            name='summary_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('error', 'Error')], default='idle', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=100)),
                ('trade_type', models.CharField(max_length=10)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('pnl', models.FloatField()),
                ('return_pct', models.FloatField(default=0.0)),
                ('total_charges', models.FloatField(default=0.0)),
                ('net_profit', models.FloatField(default=0.0)),
                ('is_paper', models.BooleanField(default=False)),
                ('duration', models.CharField(default='', max_length=20)),
                ('entry_reason', models.CharField(default='', max_length=200)),
                ('exit_reason', models.CharField(default='', max_length=200)),
                ('entry_time', models.DateTimeField(blank=True, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.livesession')),
            ],
            options={
                'ordering': ['order_id'],
                'unique_together': {('session', 'order_id')},
            },
        ),
    ]
